# Generated by Django 4.2.13 on 2024-05-30 11:10

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0004_alter_category_user_badproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badproduct',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Warehouse.product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Warehouse.category'),
        ),
        migrations.AlterField(
            model_name='incomingproduct',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Warehouse.product'),
        ),
    ]
