# Generated by Django 4.2.13 on 2024-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_badproduct_product_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bad_product_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
